name: Deploy to Firebase
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Firebase Tools
        run: npm install -g firebase-tools
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
      - name: Install Dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web

      - name: Deploy to Firebase
        run: firebase deploy --token "$FIREBASE_TOKEN" --project kapwa-companion
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}